"""empty message

Revision ID: 3341fa41d244
Revises: 
Create Date: 2022-11-24 00:03:17.561916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3341fa41d244'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_name', sa.String(length=100), nullable=False),
    sa.Column('employee_gend', sa.String(length=100), nullable=False),
    sa.Column('employee_nation', sa.String(length=100), nullable=False),
    sa.Column('employee_phone', sa.String(length=100), nullable=False),
    sa.Column('employee_birthday', sa.String(length=100), nullable=False),
    sa.Column('employee_id_card', sa.String(length=100), nullable=False),
    sa.Column('employee_bank_card', sa.String(length=100), nullable=False),
    sa.Column('employee_bank', sa.String(length=100), nullable=False),
    sa.Column('employee_address', sa.String(length=300), nullable=False),
    sa.Column('employee_occupation', sa.String(length=100), nullable=False),
    sa.Column('employee_post', sa.String(length=100), nullable=False),
    sa.Column('employee_content', sa.Text(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('attendance_days', sa.DateTime(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('attendance_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attendance_id'], ['employee_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provide_time', sa.String(length=100), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('payable', sa.DateTime(), nullable=True),
    sa.Column('actual_paid', sa.DateTime(), nullable=True),
    sa.Column('attendance_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attendance_id'], ['employee_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wages')
    op.drop_table('attendance')
    op.drop_table('employee_info')
    # ### end Alembic commands ###
