# xxxAutoConfigurartion :自动配置类，给容器中添加组件
# xxxProperties : 封装配置文件中的相关属性
spring:
  profiles:
    active: "dev"

---
spring:
  config:
    activate:
      on-profile: "dev"
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/collect-infor?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai"
    username: "root"
    password: "1234qwerasdf"
server:
  port: 8090
---
spring:
  config:
    activate:
      on-profile: "test"
server:
  port: 8091
---
spring:
  config:
    activate:
      on-profile: "prod"
server:
  port: 8092