"""empty message

Revision ID: b565d3ff2e19
Revises: 3341fa41d244
Create Date: 2022-12-08 08:37:19.693304

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b565d3ff2e19'
down_revision = '3341fa41d244'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wages')
    op.drop_table('attendance')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('attendance_days', mysql.DATETIME(), nullable=True),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('attendance_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['attendance_id'], ['employee_info.id'], name='attendance_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('wages',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('provide_time', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('payable', mysql.DATETIME(), nullable=True),
    sa.Column('actual_paid', mysql.DATETIME(), nullable=True),
    sa.Column('attendance_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['attendance_id'], ['employee_info.id'], name='wages_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
